/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import view.AddNewBooks;

/**
 *
 * @author raksha
 */
public class AdminDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminDashboard.class.getName());

    /**
     * Creates new form AdminDashboard
     */
    public AdminDashboard() {
        initComponents();
        OverviewPanel overview=new OverviewPanel(MainContentPanel);
        MainContentPanel.removeAll();
        MainContentPanel.setLayout(new BorderLayout());
        MainContentPanel.add(overview,BorderLayout.CENTER);
        MainContentPanel.revalidate();
        MainContentPanel.repaint();
        sidePanel.setVisible(false);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        //Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        //this.setSize(screenSize.width, screenSize.height);
        //jPanel1.setBounds(0, 0, this.getWidth(), this.getHeight());
        this.setVisible(true);

        //boolean isMenuOpen = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        sidePanel = new javax.swing.JPanel();
        btnBookMgmt = new javax.swing.JButton();
        btnUserMgmt = new javax.swing.JButton();
        btnIssueReturn = new javax.swing.JButton();
        btnReport = new javax.swing.JButton();
        btnSettings = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        mainContentPanel = new javax.swing.JPanel();
        MainContentPanel = new javax.swing.JPanel();
        menuButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 1200));

        jPanel1.setBackground(new java.awt.Color(238, 222, 246));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 700));

        sidePanel.setBackground(new java.awt.Color(47, 47, 47));

        btnBookMgmt.setBackground(new java.awt.Color(227, 227, 227));
        btnBookMgmt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBookMgmt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/assets/stack-of-books (1).png"))); // NOI18N
        btnBookMgmt.setText("Book Management");
        btnBookMgmt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(227, 227, 227), null, new java.awt.Color(227, 227, 227)));
        btnBookMgmt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnUserMgmt.setBackground(new java.awt.Color(227, 227, 227));
        btnUserMgmt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUserMgmt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/assets/group.png"))); // NOI18N
        btnUserMgmt.setText("User Management");
        btnUserMgmt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(227, 227, 227), null, new java.awt.Color(227, 227, 227)));
        btnUserMgmt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnIssueReturn.setBackground(new java.awt.Color(227, 227, 227));
        btnIssueReturn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnIssueReturn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/assets/discrepancy.png"))); // NOI18N
        btnIssueReturn.setText(" Issue/Return");
        btnIssueReturn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(227, 227, 227), null, new java.awt.Color(227, 227, 227)));
        btnIssueReturn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIssueReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIssueReturnActionPerformed(evt);
            }
        });

        btnReport.setBackground(new java.awt.Color(227, 227, 227));
        btnReport.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/assets/report.png"))); // NOI18N
        btnReport.setText("Reports");
        btnReport.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(227, 227, 227), null, new java.awt.Color(227, 227, 227)));
        btnReport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportActionPerformed(evt);
            }
        });

        btnSettings.setBackground(new java.awt.Color(227, 227, 227));
        btnSettings.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/assets/setting.png"))); // NOI18N
        btnSettings.setText(" Settings");
        btnSettings.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(227, 227, 227), null, new java.awt.Color(227, 227, 227)));
        btnSettings.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnLogout.setBackground(new java.awt.Color(227, 227, 227));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/assets/logout (1).png"))); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(227, 227, 227), null, new java.awt.Color(227, 227, 227)));
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLogout)
                    .addComponent(btnUserMgmt)
                    .addComponent(btnBookMgmt, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIssueReturn)
                    .addComponent(btnReport)
                    .addComponent(btnSettings))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        sidePanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnBookMgmt, btnIssueReturn, btnLogout, btnReport, btnSettings, btnUserMgmt});

        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(btnBookMgmt)
                .addGap(72, 72, 72)
                .addComponent(btnUserMgmt)
                .addGap(78, 78, 78)
                .addComponent(btnIssueReturn)
                .addGap(73, 73, 73)
                .addComponent(btnReport)
                .addGap(77, 77, 77)
                .addComponent(btnSettings)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addGap(38, 38, 38))
        );

        sidePanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnBookMgmt, btnIssueReturn, btnLogout, btnReport, btnSettings, btnUserMgmt});

        mainContentPanel.setLayout(new java.awt.CardLayout());

        MainContentPanel.setPreferredSize(new java.awt.Dimension(950, 583));

        javax.swing.GroupLayout MainContentPanelLayout = new javax.swing.GroupLayout(MainContentPanel);
        MainContentPanel.setLayout(MainContentPanelLayout);
        MainContentPanelLayout.setHorizontalGroup(
            MainContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 887, Short.MAX_VALUE)
        );
        MainContentPanelLayout.setVerticalGroup(
            MainContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        menuButton.setBackground(new java.awt.Color(238, 222, 246));
        menuButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/assets/hamburger (1).png"))); // NOI18N
        menuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(sidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(MainContentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 887, Short.MAX_VALUE)
                        .addGap(26, 26, 26))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(menuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(mainContentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainContentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(menuButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MainContentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE))
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        int choice = JOptionPane.showConfirmDialog(this, 
        "Are you sure you want to logout?", 
        "Confirm Logout", 
        JOptionPane.YES_NO_OPTION);

if (choice == JOptionPane.YES_OPTION) {
    this.dispose();
    new Login().setVisible(true);
}

    }//GEN-LAST:event_btnLogoutActionPerformed
    
    private boolean isMenuOpen = true;

    private void menuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuButtonActionPerformed
        isMenuOpen = !isMenuOpen;
        sidePanel.setVisible(isMenuOpen);
        revalidate();
        repaint();


    }//GEN-LAST:event_menuButtonActionPerformed

    private void btnIssueReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIssueReturnActionPerformed
        IssueReturn ir = new IssueReturn(); 
        MainContentPanel.removeAll();
        MainContentPanel.setLayout(new BorderLayout());
        MainContentPanel.add(ir, BorderLayout.CENTER);
        MainContentPanel.revalidate();
        MainContentPanel.repaint();
    }//GEN-LAST:event_btnIssueReturnActionPerformed

    private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed
        Reports r = new Reports(); 
        MainContentPanel.removeAll();
        MainContentPanel.setLayout(new BorderLayout());
        MainContentPanel.add(r, BorderLayout.CENTER);
        MainContentPanel.revalidate();
        MainContentPanel.repaint();
    }//GEN-LAST:event_btnReportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdminDashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainContentPanel;
    private javax.swing.JButton btnBookMgmt;
    private javax.swing.JButton btnIssueReturn;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnReport;
    private javax.swing.JButton btnSettings;
    private javax.swing.JButton btnUserMgmt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel mainContentPanel;
    private javax.swing.JButton menuButton;
    private javax.swing.JPanel sidePanel;
    // End of variables declaration//GEN-END:variables
}
