/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;
import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 *
 * @author raksha
 */
public class BookCard extends javax.swing.JPanel {
    private int bookId;

    /**
     * Creates new form BookCard
     */
    public BookCard(ImageIcon image, String title, String author, int bookId, Runnable onClick) {
        initComponents();
        this.bookId = bookId;
        setLayout(null);
        setPreferredSize(new Dimension(900, 120));
        setBackground(Color.WHITE);
        setBorder(BorderFactory.createLineBorder(Color.LIGHT_GRAY));

        JLabel cover = new JLabel(image);
        cover.setBounds(10, 10, 90, 100);
        add(cover);

        JLabel titleLabel = new JLabel("<html><b>" + title + "</b></html>");
        titleLabel.setBounds(110, 10, 500, 20);
        add(titleLabel);

        JLabel authorLabel = new JLabel("by " + author);
        authorLabel.setBounds(110, 35, 400, 20);
        add(authorLabel);

        JButton btnDetails = new JButton("View Details");
        btnDetails.setBounds(750, 70, 120, 30);
        add(btnDetails);

        btnDetails.addActionListener(e -> onClick.run());

        addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                onClick.run();
            }

            public void mouseEntered(MouseEvent e) {
                setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
                setBackground(new Color(245, 245, 245));
            }

            public void mouseExited(MouseEvent e) {
                setCursor(Cursor.getDefaultCursor());
                setBackground(Color.WHITE);
            }
        });
    }

    public int getBookId() {
        return bookId;
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
