/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.util.Base64;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import view.BrowseBooks.Book;

/**
 *
 * @author raksha
 */
public class BookCardBuy extends javax.swing.JPanel {
    int userId;
    JPanel mainPanel;
    Book book;
private boolean isExpanded = false;

    /**
     * Creates new form BookCardBuy
     */
    public BookCardBuy(Book book,int userId,JPanel mainPanel) {
        initComponents();
        this.userId=userId;
        this.mainPanel=mainPanel;
        this.book=book;
        lblTitle.setText(book.title);
        Pricelbl.setText("₹"+String.format("%.2f", book.price));
        coverImagelbl.setBorder(BorderFactory.createLineBorder(Color.GRAY, 1));
        coverImagelbl.setOpaque(true);
        coverImagelbl.setPreferredSize(new Dimension(150, 200));
        coverImagelbl.setIcon(getBookIconFromBase64(book.imagebase64));
        coverImagelbl.setBackground(Color.decode("#EEDEF6"));
        lblAuthor.setText(book.author);
        lblQuantity.setText("Quantity: "+book.quantity);
        txtDescription.setText(book.description);
        lblISBN.setText("ISBN number:"+book.isbn);
        lblGenre.setText(book.genre);
       setBorder(BorderFactory.createCompoundBorder(
    BorderFactory.createLineBorder(Color.LIGHT_GRAY, 1, true),
    BorderFactory.createEmptyBorder(10, 10, 10, 10)
));
setBackground(Color.WHITE);
setOpaque(true);
String fullDescription = book.description;
String shortText = fullDescription.length() <= 30 ? fullDescription : fullDescription.substring(0, 30);

txtDescription.setText("<html>" + shortText + "... </html>");
toggleLabel.setText("<html><u><font color='blue'>Read more</font></u></html>");
toggleLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

boolean[] isExpanded = {false};

toggleLabel.addMouseListener(new java.awt.event.MouseAdapter() {
    @Override
    public void mouseClicked(java.awt.event.MouseEvent e) {
        isExpanded[0] = !isExpanded[0];
        if (isExpanded[0]) {
            txtDescription.setText("<html><body style='width: 300px'>" + fullDescription + "</body></html>");
            toggleLabel.setText("<html><u><font color='blue'>Show less</font></u></html>");
        } else {
            txtDescription.setText("<html>" + shortText + "... </html>");
            toggleLabel.setText("<html><u><font color='blue'>Read more</font></u></html>");
        }
        txtDescription.revalidate();
    }
});

 }
    
    
    
    
    public ImageIcon getBookIconFromBase64(String base64) {
    try {
        byte[] decodedBytes = Base64.getDecoder().decode(base64);
        BufferedImage bufferedImage = ImageIO.read(new ByteArrayInputStream(decodedBytes));

        if (bufferedImage == null) {
            System.err.println("Failed to decode image — bufferedImage is null");
            return new ImageIcon();
        }

        Image scaledImage = bufferedImage.getScaledInstance(150, 200, Image.SCALE_SMOOTH);
        return new ImageIcon(scaledImage);
    } catch (Exception e) {
        e.printStackTrace();
        return new ImageIcon();
    }
}
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        coverImagelbl = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Pricelbl = new javax.swing.JLabel();
        lblAuthor = new javax.swing.JLabel();
        lblQuantity = new javax.swing.JLabel();
        lblGenre = new javax.swing.JLabel();
        lblISBN = new javax.swing.JLabel();
        txtDescription = new javax.swing.JLabel();
        toggleLabel = new javax.swing.JLabel();

        coverImagelbl.setText("bookimage");

        lblTitle.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblTitle.setText("Title");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Price paid:");

        Pricelbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Pricelbl.setText("rs.");

        lblAuthor.setText("author");

        lblQuantity.setText("quantity");

        lblGenre.setText("Genre");

        lblISBN.setText("isbn");

        toggleLabel.setText("Read More...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(coverImagelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(lblQuantity))
                    .addComponent(lblGenre)
                    .addComponent(lblTitle)
                    .addComponent(lblAuthor))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(lblISBN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Pricelbl)
                        .addGap(75, 75, 75))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(toggleLabel)
                            .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTitle)
                        .addGap(2, 2, 2)
                        .addComponent(lblAuthor)
                        .addGap(12, 12, 12)
                        .addComponent(lblGenre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(coverImagelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(toggleLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblQuantity)
                            .addComponent(lblISBN)
                            .addComponent(jLabel3)
                            .addComponent(Pricelbl))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Pricelbl;
    private javax.swing.JLabel coverImagelbl;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblAuthor;
    private javax.swing.JLabel lblGenre;
    private javax.swing.JLabel lblISBN;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel toggleLabel;
    private javax.swing.JLabel txtDescription;
    // End of variables declaration//GEN-END:variables
}
