/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import view.BrowseBooks.Book;

/**
 *
 * @author raksha
 */
public class mybooks extends javax.swing.JPanel {
    int bookId;
    int userId;
    JPanel mainPanel;
    Book book;
    private List<Book>books;
    /**
     * Creates new form 
     */
    public mybooks(List<Book>books,int userId,JPanel mainPanel) {
        initComponents();
        JScrollPane scrollPane = new JScrollPane(bookContainer);
        scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
        scrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);

        this.setLayout(new BorderLayout());
        this.add(scrollPane, BorderLayout.CENTER);

        //this.bookId=book.id;
        this.userId=userId;
        //this.book=book;
        this.mainPanel=mainPanel;
        this.books=books;
        showBooks();
        this.setMaximumSize(new Dimension(Integer.MAX_VALUE, 220)); 
       this.setAlignmentX(Component.LEFT_ALIGNMENT); 

    }
    
    private void showBooks() {
        bookContainer.setLayout(new BoxLayout(bookContainer, BoxLayout.Y_AXIS));
        bookContainer.add(Box.createVerticalStrut(10));

        bookContainer.removeAll();

        for (Book book : books) {
            BookCardBuy card = new BookCardBuy(book, userId, mainPanel);
            bookContainer.add(card);
        }
        bookContainer.revalidate();
        bookContainer.repaint();
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bookContainer = new javax.swing.JPanel();

        setBackground(new java.awt.Color(238, 222, 246));
        setPreferredSize(new java.awt.Dimension(881, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setText("My Books");

        javax.swing.GroupLayout bookContainerLayout = new javax.swing.GroupLayout(bookContainer);
        bookContainer.setLayout(bookContainerLayout);
        bookContainerLayout.setHorizontalGroup(
            bookContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 784, Short.MAX_VALUE)
        );
        bookContainerLayout.setVerticalGroup(
            bookContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 158, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bookContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(bookContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(289, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bookContainer;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
