/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.awt.BorderLayout;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import view.BookCardBuy;
import view.BrowseBooks.Book;

/**
 *
 * @author raksha
 */
public class myissuedbooks extends javax.swing.JPanel {
    int userId;
    JPanel mainPanel;
    List<Book> books;

    /**
     * Creates new form 
     */
    public myissuedbooks(List<Book> books, int userId, JPanel mainPanel) {
        initComponents();
        this.userId = userId;
        this.mainPanel = mainPanel;
        this.books = books;
        showBooks();
        JScrollPane scrollPane = new JScrollPane(bookContainer);
        scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
        scrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);

        this.setLayout(new BorderLayout());
        this.add(scrollPane, BorderLayout.CENTER);
    }
private void showBooks() {
        bookContainer.removeAll();
        bookContainer.setLayout(new BoxLayout(bookContainer, BoxLayout.Y_AXIS));

        Set<Integer> seen = new HashSet<>();
        for (Book book : books) {
            if (seen.add(book.id)) {
                BookCardBuy card = new BookCardBuy(book, userId, mainPanel);

                JPanel wrapper = new JPanel(new BorderLayout());
                wrapper.add(card, BorderLayout.CENTER);
                wrapper.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
                wrapper.setOpaque(false);

                bookContainer.add(wrapper);
                bookContainer.add(Box.createVerticalStrut(10));
            }
        }

        bookContainer.revalidate();
        bookContainer.repaint();
    
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bookContainer = new javax.swing.JPanel();

        javax.swing.GroupLayout bookContainerLayout = new javax.swing.GroupLayout(bookContainer);
        bookContainer.setLayout(bookContainerLayout);
        bookContainerLayout.setHorizontalGroup(
            bookContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 782, Short.MAX_VALUE)
        );
        bookContainerLayout.setVerticalGroup(
            bookContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 194, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bookContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(bookContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(276, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bookContainer;
    // End of variables declaration//GEN-END:variables
}
